#!/usr/bin/python

import os
import sys
import subprocess

numGames = 100;
numNodes = 9;

base = "/home/rcf-proj/ls/sorianom/go";

gamesPerNode = numGames/numNodes;
rest = numGames - gamesPerNode*numNodes;

gogui = base + "/groupGoSimple/bin/gogui-twogtp";
scriptsBase = base + "/scripts";

experiments = base + "/experiments/current/" + sys.argv[1] + "/";

arg = "-alice \"" + base + "/fuego-1.1/fuegomain/fuego --config " + base + "/configGroupGo/configSlowOneThread\" -aliceWeight " + sys.argv[2] + " -albert \"" + base + "/gnugo-3.8/interface/gnugo --mode gtp\" -albertWeight " + sys.argv[3] + " -john \"" + base + "/pachi/pachi\" -johnWeight " + sys.argv[4] + " -francesco \"" + base + "/MoGo_release3/mogo\" -francescoWeight " + sys.argv[5] + " -white \"" + base + "/fuego-1.1/fuegomain/fuego --config " + base + "/configGroupGo/configSlowOneThread\" -black \"" + base + "/fuego-1.1/fuegomain/fuego --config " + base + "/configGroupGo/configSlowOneThread\" -size 9 -auto -iteration " + sys.argv[1];

subprocess.call(["mkdir",experiments]);

initial = 0;
for n in range(numNodes):
    fb = open(scriptsBase + "/exb-" + str(n) + ".sh",'w');
    fb.write("#!/bin/sh\n\n");
    
    fb.write('cd $PBS_O_WORKDIR\n');
    if (rest > 0):
        fb.write(gogui + " " + arg + " -initial " + str(initial) + " -games " + str(gamesPerNode + 1) + " -groupColor black -sgffile " + experiments + "resultb\n");
    else:
        fb.write(gogui + " " + arg + " -initial " + str(initial) + " -games " + str(gamesPerNode) + " -groupColor black -sgffile " + experiments + "resultb\n");

    fw = open(scriptsBase + "/exw-" + str(n) + ".sh",'w');
    fw.write("#!/bin/sh\n\n");
    
    fw.write('cd $PBS_O_WORKDIR\n');
    if (rest > 0):
        fw.write(gogui + " " + arg + " -initial " + str(initial) + " -games " + str(gamesPerNode + 1) + " -groupColor white -sgffile " + experiments + "resultw\n");
    else:
        fw.write(gogui + " " + arg + " -initial " + str(initial) + " -games " + str(gamesPerNode) + " -groupColor white -sgffile " + experiments + "resultw\n");

    if (rest > 0):
        initial = initial + gamesPerNode + 1;
        rest = rest - 1;
    else:
        initial = initial + gamesPerNode;

    fb.close();
    fw.close();

    subprocess.Popen("qsub -l walltime=2:00:00,nodes=1:ppn=1,arch=x86_64 " + scriptsBase + "/exb-" + str(n) + ".sh", shell=True);
    subprocess.Popen("qsub -l walltime=2:00:00,nodes=1:ppn=1,arch=x86_64 " + scriptsBase + "/exw-" + str(n) + ".sh", shell=True);
